Models/Flavour.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace icecreamshop.Models
{
    public class Flavour
    {
        public int FlavourId { get; set; }

        [Required(ErrorMessage = "Ange namn på smak")]
        [Display(Name = "Smak")]
        public string FlavourName { get; set; }

        [Required(ErrorMessage = "Ange en förteckning över smak")]
        [Display(Name = "Beskrivning")]
        public string FlavourDescription { get; set; }

        [Required(ErrorMessage = "Ange ett pris")]
        [Display(Name = "Pris")]
        public double FlavourPrice { get; set; }

        public string PhotoPath { get; set; }

        public virtual ICollection<OrderBox> OrderBox { get; set; }//Many-to-many relationship connection
    }
}

Models/OrderBoxesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using icecreamshop.Data;

namespace icecreamshop.Models
{
    public class OrderBoxesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderBoxesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrderBoxes
        [HttpGet("order")] //Override default med annan sökväg/route
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.OrderBoxes.Include(o => o.Flavour);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: OrderBoxes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderBox = await _context.OrderBoxes
                .Include(o => o.Flavour)
                .FirstOrDefaultAsync(m => m.OrderBoxId == id);
            if (orderBox == null)
            {
                return NotFound();
            }

            return View(orderBox);
        }

        // GET: OrderBoxes/Create
        public IActionResult Create(int? id)
        {
            ViewData["FlavourId"] = new SelectList(_context.Flavour, "FlavourId", "FlavourDescription");
            return View();
        }

        // POST: OrderBoxes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderBoxId,OrderSum,OrderDate,FlavourId")] OrderBox orderBox)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderBox);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlavourId"] = new SelectList(_context.Flavour, "FlavourId", "FlavourDescription", orderBox.FlavourId);
            return View(orderBox);
        }

        // GET: OrderBoxes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderBox = await _context.OrderBoxes.FindAsync(id);
            if (orderBox == null)
            {
                return NotFound();
            }
            ViewData["FlavourId"] = new SelectList(_context.Flavour, "FlavourId", "FlavourDescription", orderBox.FlavourId);
            return View(orderBox);
        }

        // POST: OrderBoxes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderBoxId,OrderSum,OrderDate,FlavourId")] OrderBox orderBox)
        {
            if (id != orderBox.OrderBoxId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderBox);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderBoxExists(orderBox.OrderBoxId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlavourId"] = new SelectList(_context.Flavour, "FlavourId", "FlavourDescription", orderBox.FlavourId);
            return View(orderBox);
        }

        // GET: OrderBoxes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderBox = await _context.OrderBoxes
                .Include(o => o.Flavour)
                .FirstOrDefaultAsync(m => m.OrderBoxId == id);
            if (orderBox == null)
            {
                return NotFound();
            }

            return View(orderBox);
        }

        // POST: OrderBoxes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderBox = await _context.OrderBoxes.FindAsync(id);
            _context.OrderBoxes.Remove(orderBox);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderBoxExists(int id)
        {
            return _context.OrderBoxes.Any(e => e.OrderBoxId == id);
        }
    }
}

Controllers/FlavoursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using icecreamshop.Data;
using icecreamshop.ViewModels;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace icecreamshop.Models
{
    public class FlavoursController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment hostingEnviroment;//tillägg för IHostingEnviroment
        public FlavoursController(ApplicationDbContext context, IHostingEnvironment hostingEnviroment)
        {
            _context = context;
           this.hostingEnviroment = hostingEnviroment;//Deklarerar hostingEnviroment
        }

        // GET: Flavours
        /* [HttpGet("smaker")] //Override default med annan sökväg/route
          public async Task<IActionResult> Index()
          {
              return View(await _context.Flavour.ToListAsync());
          }*/

        //GET MED SÖK NY START
        // GET: Flavours
        [HttpGet("smaker")] //Override default med annan sökväg/route
        public async Task<IActionResult> Index(string searchString)//strängen skickas med som parameter i uri från startup cs routing
        {
            //queryn har definierats här men inte körts mot databasen
            var flavours = from a in _context.Flavour select a;

            //Om strängen inte är tom ska filtrering ske smak-namn
            if (!String.IsNullOrEmpty(searchString))
            {
                flavours = flavours.Where(s => s.FlavourName.Contains(searchString)); //Lambda Expression i LINQ query
            }

            return View(await flavours.ToListAsync());
        }
        //GET NY SLUT


        // GET: Flavours/Details/5
        [HttpGet("smaker/detaljer/")] //Override default med annan sökväg/route
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flavour = await _context.Flavour
                .FirstOrDefaultAsync(m => m.FlavourId == id);
            if (flavour == null)
            {
                return NotFound();
            }

            return View(flavour);
        }

        // GET: Flavours/Create
      [HttpGet("smaker/skapa")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flavours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

        [HttpPost("smaker/skapa")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(FlavourCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null; //Filnamn sätts till null initialt
                if (model.Photo != null)
                {
                  string uploadsFolder = Path.Combine(hostingEnviroment.WebRootPath, "images");//Sparar ner wwwroot path och lagrar i sträng
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;//Skapar unika filnamn för att inte overrida bilder med guid global unique identifier, varje gång GUID metoden anropas returneras ett unikt id som konverteras till sträng med tillägg för ett _ och sedan läggs uploadedFilename till
                   string filePath = Path.Combine(uploadsFolder, uniqueFileName);//Kombinerar strängarna uploadsFolder och uniqueFileName och lagrar det i en strängvariabel
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));                                                          //Kopierar uppladdad bild till image folder med metoden CopyTo i IFormFile 
                }
                Flavour newFlavour = new Flavour
                {
                    FlavourName = model.FlavourName,
                    FlavourDescription = model.FlavourDescription,
                    FlavourPrice = model.FlavourPrice,
                    PhotoPath = uniqueFileName
                };

                _context.Add(newFlavour);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        // GET: Flavours/Edit/5
      [HttpGet]
        [Authorize(Policy = "RequireAdmin")]//Kräver att man är Admin med using Microsoft.AspNetCore.Authorization;
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flavour = await _context.Flavour.FindAsync(id);
            if (flavour == null)
            {
                return NotFound();
            }
            return View(flavour);
        }

        // POST: Flavours/Edit/5
       
        [Authorize(Policy = "RequireAdmin")]//Kräver att man är Admin med using Microsoft.AspNetCore.Authorization;
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlavourId,FlavourName,FlavourDescription,FlavourPrice,PhotoPath")] Flavour flavour)
        {
            if (id != flavour.FlavourId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flavour);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlavourExists(flavour.FlavourId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flavour);
        }

        // GET: Flavours/Delete/5
        [Authorize(Policy = "RequireAdmin")]//Kräver att man är Admin med using Microsoft.AspNetCore.Authorization;
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flavour = await _context.Flavour
                .FirstOrDefaultAsync(m => m.FlavourId == id);
            if (flavour == null)
            {
                return NotFound();
            }

            return View(flavour);
        }

        // POST: Flavours/Delete/5
        [Authorize(Policy = "RequireAdmin")]//Kräver att man är Admin med using Microsoft.AspNetCore.Authorization;
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flavour = await _context.Flavour.FindAsync(id);
            _context.Flavour.Remove(flavour);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlavourExists(int id)
        {
            return _context.Flavour.Any(e => e.FlavourId == id);
        }
    }
}

Views/Flavours/Create.cshtml
@model icecreamshop.ViewModels.FlavourCreateViewModel

@{
    ViewData["Title"] = "Lägg till ny smak";
}

<h1>Lägg till ny smal</h1>

<h4>Smaker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FlavourName" class="control-label"></label>
                <input asp-for="FlavourName" class="form-control" />
                <span asp-validation-for="FlavourName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlavourDescription" class="control-label"></label>
                <input asp-for="FlavourDescription" class="form-control" />
                <span asp-validation-for="FlavourDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlavourPrice" class="control-label"></label>
                <input asp-for="FlavourPrice" class="form-control" />
                <span asp-validation-for="FlavourPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="Photo" class="form-control custom-file-input" />
                    <label class="custom-file-label">Välj fil...</label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Skapa smak" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka till lista</a>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
    }
</div>

Views/Flavours/Delete.cshtml
@model icecreamshop.Models.Flavour

@{
    ViewData["Title"] = "Delete";
}

<h1>Ta bort smak</h1>

<h3>Är du säker på att du vill ta bort smaken?</h3>
<div>
    <h4>Smak du kommer att ta bort</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlavourName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlavourName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlavourDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlavourDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlavourId" />
        <input type="submit" value="Ta bort" class="btn btn-danger" /> |
        <a asp-action="Index">Tillbaka till smaker</a>
    </form>
</div>

Views/Flavours/Details.cshtml
@model Flavour
@{
    ViewData["Title"] = "Smakfull information";
    var photoPath = "~/images/" + (Model.PhotoPath ?? "glass2.jpg");
}

<h1>Detaljer</h1>

<div class="justify-content-center">
    <h4>Smakfull information</h4>

    <div class="justify-content-center" style="width: 18rem;">
        <div class="card text-center">
            <div class="card-header">
                <h5 class="card-title">@Html.DisplayFor(model => model.FlavourName)</h5>
            </div>
            <div class="card-body text-center">
                <img class="card-img-top" src="@photoPath" alt="glassbild" asp-append-version="true" /><br />

            </div>
            <div class="card-footer text-muted">
                <h5>@Html.DisplayNameFor(model => model.FlavourDescription)</h5><br />

                <p class="card-text">@Html.DisplayFor(model => model.FlavourDescription)</p><br /><br />

                <p class="card-text" style="color: #ff008a;font-weight: 800;">@Html.DisplayFor(model => model.FlavourPrice)kronor/strut</p>
            </div>
        </div>
    </div>

    <div>
        @if (User.Identity.Name == "Admin@mail.com")
        {
            <a asp-action="Edit" asp-route-id="@Model.FlavourId"><i class="fas fa-edit"></i></a>
        }
        <a asp-action="Index"><i style="font-size:2em;" class="fas fa-arrow-circle-left"></i></a>
    </div>
</div>

Views/Flavours/Edit.cshtml
@model icecreamshop.Models.Flavour

@{
    ViewData["Title"] = "Ändra smak";
}

<h1>Ändra smak</h1>

<h4>Smaker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input style="display:none;" asp-for="FlavourId" />
            <div class="form-group">
                <label asp-for="FlavourName" class="control-label"></label>
                <input asp-for="FlavourName" class="form-control" />
                <span asp-validation-for="FlavourName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlavourPrice" class="control-label"></label>
                <input asp-for="FlavourPrice" class="form-control" />
                <span asp-validation-for="FlavourPrice" class="text-danger"></span>
            </div>
            <div style="display:none;" class="form-group">
                <label asp-for="PhotoPath" class="control-label"></label>
                <input asp-for="PhotoPath" class="form-control" />
                <span asp-validation-for="PhotoPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlavourDescription" class="control-label"></label>
                <input asp-for="FlavourDescription" class="form-control" />
                <span asp-validation-for="FlavourDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka till smaker</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Flavours/Index.cshtml
@model IEnumerable<icecreamshop.Models.Flavour>
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Våra smaker";
}

<h1 style="text-align:center; margin-bottom:7%;">Våra smaker</h1>


@if (User.Identity.Name == "Admin@mail.com")
{
    <p style="text-align:right; display:block;">
        <a asp-action="Create">Lägg till ny smak</a>
    </p>
}


<!--Formulär för sökfunktion start-->
<form id="searchform" asp-controller="Flavours" asp-action="Index" method="get">
    <p>
        Sök smak: <input class="searchforminput" type="text" name="SearchString">
        <input type="submit" id="searchbutton" value="Sök"/>
    </p>
</form>
<!--Formulär för sökfunktion slut-->



<div class="card-deck">
    <div class="row justify-content-center m-3">
        @foreach (var item in Model)
        {
            var photoPath = "~/images/" + (item.PhotoPath ?? "glass2.jpg");

            <div class="card" style="min-width: 18rem; max-width: 30.5%; margin-bottom: 2%;">
                <div class="card-header">
                    <h3>@Html.DisplayFor(modelItem => item.FlavourName)</h3>
                </div>
                <div class="card-body text-center">
                    <img class="card-img-top" src="@photoPath" alt="glassbild" asp-append-version="true" />
                    <div class="card-body text-center">
                        <p>   @Html.DisplayFor(modelItem => item.FlavourPrice)kronor/strut</p>
                    </div>
                </div>
                <div class="card-footer text-center">
                    @if (User.Identity.Name == "Admin@mail.com")
                    {
                        <a asp-action="Edit" asp-route-id="@item.FlavourId"><i class="fas fa-edit"></i></a>
                    }
                    <a asp-action="Details" asp-route-id="@item.FlavourId"><i class="fas fa-ice-cream"></i> info</a>
                    @if (User.Identity.Name == "Admin@mail.com")
                    {
                        <a asp-action="Delete" asp-route-id="@item.FlavourId"><i class="fas fa-trash"></i></a>
                    }
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a class="buyButton" asp-controller="OrderBoxes" asp-action="Create" asp-route-id="@item.FlavourId">Köp</a>
                    }
                </div>

            </div>

        }
    </div>
</div>